#!/bin/bash
# Managed by Ansible

# https://medium.com/@aiguofer/flawless-bluetooth-headset-mdr-100abn-on-linux-e745cb746671
# https://gitlab.freedesktop.org/pulseaudio/pulseaudio/issues/525

BT_DEVICE_ADDR=$(pacmd list-cards | grep -i 'name:.*bluez_card' | sed -E 's/.*<?bluez_card\.([A-Z0-9_]+)>?/\1/')
# device_mac=$(echo $BT_DEVICE_ADDR | sed 's/_/:/g')

A2DP_AVAILABLE=$(pacmd list-cards | grep -A30 bluez | grep "A2DP Sink" | sed -E 's/.* available: ([a-z]+)\)/\1/g')

if [[ "$A2DP_AVAILABLE" == "no" ]] || [[ "$A2DP_AVAILABLE" == "unknown" ]]; then
    dbus-send --system --dest=org.bluez --print-reply "/org/bluez/hci0/dev_${BT_DEVICE_ADDR}" org.bluez.Device1.Connect

    pacmd set-card-profile "bluez_card.${BT_DEVICE_ADDR}" off
    pacmd set-card-profile "bluez_card.${BT_DEVICE_ADDR}" a2dp_sink
    pacmd set-default-sink "bluez_sink.${BT_DEVICE_ADDR}.a2dp_sink"
fi
