# Molecule managed

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

RUN echo 'Server = https://mirrors.dotsrc.org/archlinux/$repo/os/$arch' > /etc/pacman.d/mirrorlist \
    && pacman -Sy --noconfir --noprogressbar \
    && pacman -S --noconfirm --noprogressbar python sudo
